export const products = [
  {
    name: "wireless earbuds",
    price: 45,
    company: "soundcore",
    rating: 4.2,
  },
  {
    name: "smart TV",
    price: 650,
    company: "samsung",
    rating: 4.7,
  },
  {
    name: "laptop",
    price: 999,
    company: "apple",
    rating: 4.8,
  },
  {
    name: "gaming chair",
    price: 200,
    company: "razer",
    rating: 4.5,
  },
  {
    name: "bluetooth speaker",
    price: 65,
    company: "bose",
    rating: 4.4,
  },
  {
    name: "smartphone",
    price: 799,
    company: "google",
    rating: 4.3,
  },
  {
    name: "robot vacuum",
    price: 150,
    company: "roomba",
    rating: 4.6,
  },
  {
    name: "4K projector",
    price: 1200,
    featured: true,
    company: "benq",
    rating: 4.9,
  },
  {
    name: "smart thermostat",
    price: 120,
    featured: true,
    company: "nest",
    rating: 4.1,
  },
  {
    name: "smartwatch",
    price: 180,
    company: "fitbit",
    rating: 4.3,
  },
  {
    name: "wireless charging pad",
    price: 65,
    featured: true,
    company: "anker",
    rating: 4.8,
  },
  {
    name: "home security camera",
    price: 85,
    company: "arlo",
    rating: 4.6,
  },
  {
    name: "noise-cancelling headphones",
    price: 300,
    company: "sony",
    rating: 4.7,
  },
  {
    name: "fitness tracker",
    price: 100,
    company: "garmin",
    rating: 4.4,
  },
  {
    name: "tablet",
    price: 250,
    company: "samsung",
    rating: 4.6,
  },
  {
    name: "portable power bank",
    price: 50,
    company: "mophie",
    rating: 4.5,
  },
  {
    name: "smart speaker",
    price: 120,
    featured: true,
    company: "amazon",
    rating: 4.9,
  },
  {
    name: "wireless mouse",
    price: 25,
    featured: true,
    company: "logitech",
    rating: 4.6,
  },
  {
    name: "digital camera",
    price: 500,
    company: "canon",
    rating: 4.3,
  },
  {
    name: "external hard drive",
    price: 150,
    company: "seagate",
    rating: 4.4,
  },
  {
    name: "gaming monitor",
    price: 400,
    company: "asus",
    rating: 4.5,
  },
  {
    name: "smart light bulbs",
    price: 50,
    company: "philips",
    rating: 4.7,
  },
  {
    name: "electric toothbrush",
    price: 120,
    company: "oral-b",
    rating: 4.8,
  },
  {
    name: "soundbar",
    price: 250,
    company: "sony",
    rating: 4.6,
  },
];
